micronaut:
  application:
    name: bytearrayR2dbcIssue
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      url: r2dbc:postgresql://localhost:5432/postgres
      username: postgres
      password: ''
netty:
  default:
    allocator:
      max-order: 3
